### ISSUE TITLE
Problema no resultado de busca Micromedex

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/psbe-metasearch#2]
Ao buscar no metabuscador a palavra atenolol, os resultados no metabuscador para a fonte de informação Micromedex retorna "nenhum resultado encontrado".

**Comment by viniciusandrade** [comment]
Informado novo caso onde a busca não retorna resultados para nome de marca. Exemplo "clexane".

**Comment by renatomurasaki** [comment]
Novos casos de uso para busca na base Micromedex integrada no Metabuscador:

- benzodiazepines
- hipertensão (hypertension está ok)
- drug interactions
- drugs that treat colorectal cancer
- drugs that cause colorectal cancer

**Comment by viniciusandrade** [comment]
Novos casos resolvidos em https://github.com/bireme/psbe-metasearch/commit/4485861e0f9d37e8ca599f5783e387ebe93c56fe
